### ISSUE TITLE
Can I have events triggered from different instances of Python CLI's?

### ISSUE THREAD

**Issue by eabase** [pyeve/events#21]
Is it possible to trigger an event listener from a different Python CLI (or program) than where the listener was launched from?

**Comment by ajpen** [comment]
To do that, you would need to manually set up some form of communication between the applications. `Events` only operate within the process it was instantiated in.

**Comment by eabase** [comment]
I see. Thank you @ajpen !

So another, perhaps related question, is the following. 

If I have a *subscribed* to an event in the standard way, like so: `events.on_change += something_changed`, in which *"way"* am I notified when there is an *event*?  As I see it, there are only 2 options:

1. Your code should sit there waiting for this event, until triggered. Assuming single thread processing, nothing happens and nothing else can be processed until the event happens.

2. The event only subscribed to *"a newspaper"*, that does occur, but at an unknown time. In this case your code just keep on going after the subscription, and you need to run it in your own loop before finishing program if you are going to get any notification. Also, would it be right to assume a polling function is not needed as it is handled by the event/listener framework itself? 

It's possible I am not formulating this question very well, but I guess it relates to weather or not this subscription is blocking or just happens at some (externally timed event).

**Comment by ajpen** [comment]
Events does not operate concurrently at the moment. If you have a few callbacks subscribed to an event, triggering that event (with say `events.on_change('it had to happen')`) merely calls the functions subscribed to that event with the parameter `"it had to happen"`. It happens in the same thread that triggered the event.

If you wish to have any sort of concurrency, such as a pubsub across threads, you would need to implement that.

I hope this answers your question.
